<robot name="vacuumcleaner" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="inertial_disk" params="mass radius height orientation">
    <inertial>
      <origin rpy="${orientation}" xyz="0 0 0" />
      <mass value="${mass}" />
      <inertia
        ixx="${1/12 * mass * (3* radius * radius + height * height)}"
        ixy="0"
        ixz="0"
        iyy="${1/12 * mass * (3* radius * radius + height * height)}"
        iyz="0"
        izz="${1/2 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>

  <xacro:property name="body_height" value="0.04"/>
  <xacro:arg name="body_radius" default="0.2" />
  <xacro:macro name="wheel" params="suffix radius xoffset yoffset zoffset">
     <link name="link_${suffix}_wheel">
     <xacro:inertial_disk mass="0.1" radius="${radius}" height="0.018" orientation="0 1.5757 1.5757"/>
  
     <collision name="link_right_wheel_collision">
        <origin rpy="0 1.5757 1.5757" xyz="0 0 0" />
        <geometry>
          <cylinder length="0.018" radius="${radius}" />
        </geometry>
      </collision>
      <visual name="link_right_wheel_visual">
        <origin rpy="0 1.5757 1.5757" xyz="0 0 0" />
        <geometry>
          <cylinder length="0.018" radius="${radius}" />
        </geometry>
      </visual>
    </link>
    <gazebo reference="link_${suffix}_wheel">
       <mu1>100000</mu1>
       <mu2>100000</mu2>
       <kp>1e5</kp>
       <material>Gazebo/Black</material>
    </gazebo>
    <joint name="joint_${suffix}_wheel" type="continuous">
       <origin rpy="0 0 0" xyz="${xoffset} ${yoffset} ${zoffset}" />
       <child link="link_${suffix}_wheel" />
       <parent link="base_footprint" />
       <axis rpy="0 0 0" xyz="0 1 0" />
       <limit effort="10000" velocity="1000" />
    </joint>
  </xacro:macro>

  <xacro:wheel suffix="left" radius="0.033" xoffset="-0.01" yoffset="${($(arg body_radius)-0.16)}" zoffset="-0.054"/>
  <xacro:wheel suffix="right" radius="0.033" xoffset="-0.01" yoffset="${-($(arg body_radius)-0.16)}" zoffset="-0.054"/>

  <link name="base_footprint">
    <xacro:inertial_disk mass="2" radius="$(arg body_radius)" height="${body_height}" orientation="0 0 0"/>
    <visual>
      <geometry>
	      <cylinder length="${body_height}" radius="$(arg body_radius)" />
      </geometry>
    </visual>
    <collision>
      <geometry>
	      <cylinder length="${body_height}" radius="$(arg body_radius)" />
      </geometry>
    </collision>
    <collision name="caster_front_collision">
      <origin rpy="0 0 0" xyz="${$(arg body_radius)-0.03} 0 -0.054" />
      <geometry>
        <sphere radius="0.033" />
      </geometry>
    </collision>
    <visual name="caster_front_visual">
      <origin rpy="0 0 0" xyz="${$(arg body_radius) - 0.03} 0 -0.054" />
      <geometry>
        <sphere radius="0.033" />
      </geometry>
    </visual>
  </link>
  <gazebo>
   <plugin name="differential_drive" filename="libgazebo_ros_diff_drive.so">
      <rosDebugLevel>na</rosDebugLevel>	     
      <updateRate>30</updateRate>
      <leftJoint>joint_left_wheel</leftJoint>
      <rightJoint>joint_right_wheel</rightJoint>
      <wheelSeparation>${ $(arg body_radius)*2 - 0.16*2}</wheelSeparation>
      <wheelDiameter>0.066</wheelDiameter>
      <wheelTorque>20</wheelTorque>
      <wheelAcceleration>0.1</wheelAcceleration>
      <commandTopic>/cmd_vel</commandTopic>
      <publishOdom>true</publishOdom>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelTF>false</publishWheelTF>
      <odometryTopic>/odom</odometryTopic>
      <odometryFrame>/odom</odometryFrame>
      <robotBaseFrame>/base_footprint</robotBaseFrame>
    </plugin>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <updateRate>30</updateRate>
      <jointName>joint_left_wheel, joint_right_wheel</jointName>
    </plugin>
  </gazebo>
  <link name="base_scan">
    <visual>
      <geometry>
        <sphere radius="0.05" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.05" />
      </geometry>
    </collision>
    <xacro:inertial_disk mass="0.001" radius="0.05" height="0.018" orientation="0 0 0"/>
  </link>
  <joint name="base_scan_joint" type="fixed">
    <child link="base_scan" />
    <parent link="base_footprint" />
    <origin xyz="0 0 0.051" />
    <!-- +0.051 iso 0.05 otherwise vision clips into top of robot-->
  </joint>
  <gazebo reference="base_scan">
    <sensor name="raycaster" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>3.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="laserscan" filename="libgazebo_ros_laser.so">
	<topicName>scan</topicName>
	<frameName>base_scan</frameName>
      </plugin>
   </sensor>
  </gazebo>
</robot>
