TrajectoryPlannerROS:
  max_vel_x: 0.2 # m/s 
  min_vel_x: 0.01 # minimum to send to base m/s
  max_vel_y: 0.2 # m/s 
  min_vel_y: 0.01 # minimum to send to base m/s

  acc_lim_theta: 1.0 # m/s²
  acc_lim_x: 1.0 # m/s²
  acc_lim_y: 1.0 # m/s²
  latch_xy_goal_tolerance: true

  holonomic_robot: false
