obstacle_range: 2.0 # maximum sensor reading that will result in an obstacle begint put in the costmap
raytrace_range: 3.5 # range to which freespace is raytraced given a sensor reading

robot_radius: 0.2
inflation_radius: 0.1 #All paths that stay away n-meters from obstacle have equal cost
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
