global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  publish_frequency: 1.0
  update_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.4
