local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 0.5
  height: 0.5
  resolution: 0.4
